<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
    use FavoriteTrait;
    use RecordsActivity;

    protected $with = ['owner' , 'favorites'];

    protected $appends = ['favoritesCount' , 'isFavorited'];

    protected $guarded = [];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

//        static::created(function($reply){
//           $reply->thread->increment('replies_count');
//        });
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function thread()
    {
        return $this->belongsTo(Thread::class);
    }

    public function logDeleteActivity()
    {
        $this->recordActivity('deleted');
    }





}
